import "@/styles/globals.css";

import { Inter } from "next/font/google";
import { cookies } from "next/headers";

import { TRPCReactProvider } from "@/trpc/react";
import { NavHeader } from "./_components/NavHeader";
import { Footer } from "./_components/Footer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Hirely",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body className={`font-sans ${inter.variable} h-full`}>
        <TRPCReactProvider cookies={cookies().toString()}>
          <NavHeader>
            <Footer>{children}</Footer>
          </NavHeader>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
